services:
  niyaku-db:
    image: postgres:15
    container_name: niyaku-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - niyaku_postgres_data:/var/lib/postgresql/data

  niyaku-redis:
    image: redis:alpine
    container_name: niyaku_redis_cache
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - niyaku_redis_data:/data

volumes:
  niyaku_postgres_data:
  niyaku_redis_data: