services:
  niyaku-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: niyaku-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      niyaku-db:
        condition: service_healthy
      niyaku-redis:
        condition: service_started

  niyaku-db:
    image: postgres:15
    container_name: niyaku-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - niyaku_postgres_data:/var/lib/postgresql/data

  niyaku-redis:
    image: redis:alpine
    container_name: niyaku_redis_cache
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379"
    volumes:
      - niyaku_redis_data:/data

volumes:
  niyaku_postgres_data:
  niyaku_redis_data: